#!/usr/bin/env bash
# Download KataGo binary + a compatible neural net for local WSL/Linux development.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INSTALL_DIR="${KATAGO_INSTALL_DIR:-$ROOT/third_party/katago}"
KATAGO_VERSION="${KATAGO_VERSION:-1.16.4}"
KATAGO_BUILD="${KATAGO_BUILD:-eigenavx2}"
MODEL_NAME="${KATAGO_MODEL_NAME:-kata1-b20c256x2-s4384473088-d968438914.bin.gz}"

KATAGO_ZIP="katago-v${KATAGO_VERSION}-${KATAGO_BUILD}-linux-x64.zip"
KATAGO_URL="https://github.com/lightvector/KataGo/releases/download/v${KATAGO_VERSION}/${KATAGO_ZIP}"
MODEL_URL="https://media.katagotraining.org/uploaded/networks/models/kata1/${MODEL_NAME}"

mkdir -p "$INSTALL_DIR"

download() {
    local url="$1"
    local dest="$2"
    if [[ -f "$dest" ]]; then
        echo "Already present: $dest"
        return 0
    fi
    echo "Downloading $url"
    curl -fL --retry 3 --retry-delay 2 -o "$dest" "$url"
}

echo "Installing KataGo under: $INSTALL_DIR"

zip_path="$INSTALL_DIR/$KATAGO_ZIP"
download "$KATAGO_URL" "$zip_path"

if [[ ! -x "$INSTALL_DIR/katago" ]]; then
    echo "Extracting $KATAGO_ZIP"
    if command -v unzip >/dev/null 2>&1; then
        unzip -o -q "$zip_path" -d "$INSTALL_DIR"
    else
        python3 -m zipfile -e "$zip_path" "$INSTALL_DIR"
    fi
    chmod +x "$INSTALL_DIR/katago"
fi

model_path="$INSTALL_DIR/$MODEL_NAME"
download "$MODEL_URL" "$model_path"

config_path="$ROOT/third_party/katago/analysis.cfg"
if [[ ! -f "$config_path" ]]; then
    echo "Missing analysis config: $config_path" >&2
    exit 1
fi

env_file="$ROOT/.env"
if [[ ! -f "$env_file" ]]; then
    cat >"$env_file" <<EOF
# Local KataGo paths (generated by scripts/setup_katago.sh)
KATAGO_BINARY_PATH=$INSTALL_DIR/katago
KATAGO_CONFIG_PATH=$config_path
KATAGO_MODEL_PATH=$model_path
EOF
    echo "Wrote $env_file"
else
    echo "Leaving existing $env_file unchanged."
    echo "Expected paths after setup:"
    echo "  KATAGO_BINARY_PATH=$INSTALL_DIR/katago"
    echo "  KATAGO_CONFIG_PATH=$config_path"
    echo "  KATAGO_MODEL_PATH=$model_path"
fi

echo ""
echo "KataGo setup complete."
echo "Verify with:"
echo "  source .venv/bin/activate"
echo "  set -a && source .env && set +a"
echo "  pytest tests/integration/test_katago_smoke.py -m integration -v"
